[project]
name = "offline-cloud-computing"
version = "0.1.0"
description = "(CLOUD COMPUTING 2026) Offline Cloud Computing Equipo 5 Grupo 503"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.14.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.21.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.7",
    "notebook>=7.5.6",
]
